#!/system/xbin/bash
#!/system/xbin/botbrew
#!/website : unknown240.github.io
clear
curl -O https://de1.androidfilehost.com/dl/e3hcFx9QjyvheOzp7faRsA/1564378855/6006931924117919402/v1.5.7z
unzip v1.5.zip
cd v1.5
bash index
